language: java
jdk:
  - openjdk8
  - openjdk9
addons:
  sonarcloud:
    organization: "djangooutplayed"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=djangooutplayed
